<?php
/**
 * @file
 * Module file for plus_search_simple2.
 */


function plus_search_simple2_menu(){
    return array(
        'admin/build/something' => array(
            'title' => 'Example Admin Form',
            'description' => 'Admin form introduced by the MODULENAME module',
            'type' => MENU_NORMAL_ITEM,
            'page callback' => 'drupal_get_form',
            'access arguments' => array('access administration pages'),
        ),
    );


/**
 * Implements hook_block_info().
 */
function plus_search_simple2_block_info() {
  $blocks['form']['info'] = t('FX Plus Simple Catalog Search with menu');
  // Not worth caching.
  $blocks['form']['cache'] = DRUPAL_NO_CACHE;
  $blocks['form']['properties']['administrative'] = TRUE;
  return $blocks;
}
/**
 * Implements hook_block_view().
 */
function plus_search_simple2_block_view($delta = '') {
  if (user_access('search content')) {
    $search_options = theme(
      'links__menu_quick_links', 
      array('links' => menu_navigation_links('menu-search-menu')
    ));
    $search_form = drupal_get_form('plus_search_simple2_block_form');

    $search_form['submit'] = $search_form['actions']['submit'];
    $search_form['submit']['#weight'] = 1;
    $search_form['submit']['#attributes']['class'] = array('pull-left');

    unset($search_form['actions']['submit']);

    $search_form['search_options']['#prefix'] = '<div class="pull-left">';
    $search_form['search_options']['#suffix'] = '</div>';
    $search_form['search_options']['#markup'] = $search_options;
    $search_form['search_options']['#weight'] = 9;
    $search_form['search_options']['#attributes']['class'] = array('pull-left');


    $block['content'] = $search_form;
    return $block;
  }
}
/**
 * Implements hook_forms().
 */
function plus_search_simple2_forms() {
  $forms['plus_search_simple2_block_form']= array(
    'callback' => 'plus_search_simple2_box',
    'callback arguments' => array('plus_search_simple2_block_form'),
  );
  return $forms;
}
/**
 * Form builder; Output a search form for the search block's search box.
 */
function plus_search_simple2_box($form, &$form_state, $form_id) {
  // todo replace add_css with theme function?
  // drupal_add_css(drupal_get_path('module', 'plus_search_simple2').'/plus_search_simple2.css');
  $form['plus_search_simple2_form'] = array(
    '#type' => 'textfield',
    '#title' => 'Search The Library Catalogue',
    '#title_display' => 'invisible',
    '#default_value' => '',
    '#attributes' => array(
      'title' => t('Search the library'), 
      'placeholder' => t('search the library'),
      'class' => array(
         'search-query',
      ),
    ),
  );
  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array('#type' => 'submit', '#value' => t('Search'));
  $form['#submit'] = array('plus_search_simple2_search_box_form_submit');
  return $form;
}
function plus_search_simple2_search_box_form_submit($form, &$form_state) {
  $searchterm = $form_state['values']['plus_search_simple2_form'];
  _plus_search_query_catalog($searchterm);
}
